# Generated by Django 3.1.3 on 2020-11-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
